#!/usr/bin/env bash
echo running install check
# ensure package.json exits
if [[ -f "./package.json" ]]; then
    false;
else
    npm init -y
fi

mkdir -p ./settings/.cache
HASH_PATH="./settings/.cache/.nosync.node_modules_hash"
# ensure .nosync.node_modules_hash exists
if [[ -f "$HASH_PATH" ]]; then
    false;
else
    touch "$HASH_PATH"
fi
# check if need to do npm install
old_node_modules_hash="$(cat "$HASH_PATH")"
new_node_modules_hash="$(cat package.json | md5sum)"
if [[ "$old_node_modules_hash" != "$new_node_modules_hash" ]]; then
    echo "$new_node_modules_hash" > "$HASH_PATH"
    npm install
fi