#!/usr/bin/env bash
echo running install check
# ensure package.json exits
if [[ -f "./package.json" ]]; then
    false;
else
    npm init -y
fi
# ensure .nosync.node_modules_hash exists
if [[ -f ".nosync.node_modules_hash" ]]; then
    false;
else
    touch ".nosync.node_modules_hash"
fi
# check if need to do npm install
old_node_modules_hash="$(cat .nosync.node_modules_hash)"
new_node_modules_hash="$(cat package.json | md5sum)"
if [[ "$old_node_modules_hash" != "$new_node_modules_hash" ]]; then
    echo "$new_node_modules_hash" > ".nosync.node_modules_hash"
    npm install
fi