#!/usr/bin/env bash
# summary
#   this should be a kind of nuclear option 
#   - if its not part of the git repo
#   - and it will take a long time (>1min) to get the data back
#   => this command should get rid of it
# 


# clean all the small things
./commands/clean

# node
rm -rfv "node_modules"